version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mtburls-ruby"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ps89mbz9rcth"
s3_prefix = "mtburls-ruby"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
