AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mtburls-ruby-sam

  Sample SAM Template for mtburls-ruby-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  MtbUrlsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: mtburls/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Architectures:
        - x86_64
      Events:
        MtbSiteUrl:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /site
            Method: get
            RestApiId:
               Ref: MtbApi
            RequestParameters:
              - method.request.querystring.type:
                  Required: false
                  Caching: true
  MtbApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      CacheClusterEnabled: true
      CacheClusterSize: "1.6"
      MethodSettings: 
         - ResourcePath: /
           CachingEnabled: true
           CacheTtlInSeconds: 1000
           HttpMethod: "GET"
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'content-type'"
        AllowOrigin: "'*'"
        AllowCredentials: false

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MtbUrlsApi:
    Description: "API Gateway endpoint URL for Prod stage for MTBURLS function"
    Value: !Sub "https://${MtbApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/site"
  MtbUrlsFunction:
    Description: "MTBURLS Lambda Function ARN"
    Value: !GetAtt MtbUrlsFunction.Arn
  MtbUrlsFunctionIamRole:
    Description: "Implicit IAM Role created for MTBURLS function"
    Value: !GetAtt MtbUrlsFunctionRole.Arn
